version: "3.6"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - web
    #ports:
      #- "8000:80"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`finance-skills.ru`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

networks:
  web:
    name: web
    external: true

